server:
  port: 8088
  mode: "debug" # debug 或 release

mysql:
  dsn: "root:G20050111g@tcp(127.0.0.1:3306)/agentic_rag?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conns: 10
  max_open_conns: 100

redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0
  pool_size: 10

llm:

  # DeepSeek
  api_key: "sk-2fcda97a277d40c59b7f16b281b98966"
  model: "deepseek-chat"
  base_url: "https://api.deepseek.com/anthropic"